### ISSUE TITLE
Sensors error

### ISSUE THREAD

**Issue by japenn82** [sbski/Renoir-Mobile-Tuning#24]
When I run the sensors within the program, I get an error about not being able to find the CurrentSettings.json file.

BTW, I want to thank the dev for the app. It works great on my G14, especially when I'm running on battery!

![image](https://user-images.githubusercontent.com/62119601/105511057-79527500-5c9d-11eb-972d-9696d665b9a3.png)

**Comment by CopticWalad** [comment]
I have the same issue.  Never had the program before nd found there is no CurrentSettings.json file in current version after unzipping.  This also happens when opened with Admin.

**Comment by Dark4Codrutz** [comment]
I happened to delete the file. Apparently the software never recreates it in case of the file missing and plainly tries to open it.
For me that file was generated on first run. Gladly I could restore it easily.
There seems to be a state somewhere saved in the OS (registry ?) so it knows it's not the first time running.

**Comment by sbski** [comment]
I resolved this issue with version 1.1.0. It was me rushing it out and then forgetting that this was an issue the first time I did it.
