### ISSUE TITLE
Some advice and thk

### ISSUE THREAD

**Issue by Aragamiz** [sbski/Renoir-Mobile-Tuning#3]
hope this tool can lock if freq or GFX freq save more power when i ues less . and thk for dev~

**Comment by sbski** [comment]
I am going to look into it more. I am currently working on optimizing the code so that it 1: runs faster and 2: can get more features. 
I just need to do some more testing then version 0.3.0 will come out. It is functionally the same but you will be able to tell if the settings actually applied!

**Comment by sbski** [comment]
> hope this tool can lock if freq or GFX freq save more power when i ues less . and thk for dev~

The gfx can now be locked and it's come a far way since the old days of RMT
