### ISSUE TITLE
Failed to load InpOutx64 driver. Please check that the application is running with the right privledges. 

### ISSUE THREAD

**Issue by supmanyu** [sbski/Renoir-Mobile-Tuning#30]
I play Valorant which is made by riot games, and its anti-cheat (Riot Vanguard) software blocks this application from running.

[PMTableDump.log](https://github.com/sbski/Renoir-Mobile-Tuning/files/6873576/PMTableDump.log)

**Comment by orangpelupa** [comment]
try adding renoir mobile tuning folder into your antivirus' whitelist
