### ISSUE TITLE
WILL IT SUPPORT R 5000 LAPTOP ? @sbski

### ISSUE THREAD

**Issue by n0m4ad** [sbski/Renoir-Mobile-Tuning#32]

**Comment by Bobu5** [comment]
yes, it will, why wouldnt it? i have a Ryzen 3 5300U laptop , it works fine with it, but idk why the iGPU option doesnt work for me, still trying to figure it out till today

**Comment by sbski** [comment]
It now has support for ALL Ryzen 2000-6000 CPUs.
The power monitoring doesn't work properly on anything but 4000 series and the 5300u, 5500u, and 5700u.
