### ISSUE TITLE
[Question] A Question regarding the iGPU overclocking option

### ISSUE THREAD

**Issue by Bobu5** [sbski/Renoir-Mobile-Tuning#34]
hi there, i dont know why but the iGPU overclocking option doesnt seems to work for me , it would always spit `CMD_REJECTED_` in the log 
![image](https://user-images.githubusercontent.com/87025837/146696272-742594f3-2882-4b06-b770-340611a2ee9c.png)
im currently using a HP Pavilion ac0008AU , heres the spec:
Ryzen 3 5300U 
2x4GB DDR4 3200Mhz
some Samsung 512gb nvme SSD

and heres my log PMTableDump log [https://pastebin.com/raw/mDtpehDP]

Let me know if u need any additional info about it, and once again thanks in regard

**Comment by sbski** [comment]
For no known reason, the SMU will have a fit and not want to apply a setting... It's annoying but I would like to look into it further at some point.
