### ISSUE TITLE
Autostart app

### ISSUE THREAD

**Issue by persona-ny** [sbski/Renoir-Mobile-Tuning#5]
Hi, tell me how to set the value of temp-85 and tdp-35 for autorun? It is not very convenient to run the program every time and set the values

**Comment by sbski** [comment]
I am working on a solution to this as we speak.

**Comment by kingweee** [comment]
That would be a great feature. Could you also add minimize to tray functionality? I have a specific app that force minimizes things to the tray but for whatever reason it doesn't work with RMT.
