### ISSUE TITLE
Hi. can i run this using command?

### ISSUE THREAD

**Issue by dmsalsgh97** [sbski/Renoir-Mobile-Tuning#6]
Hi all 
I'm writing my own .bat file for my longger battery mode.
Can I run this with windows cmd command? 

thx for building and maintaining this rool 👍

**Comment by sbski** [comment]
@dmsalsgh97 Yes and no. Your best bet is going to be RyzenAdj. That is a CLI based solution that this is HEAVILY based off of. I am also a maintainer and researcher for RyzenAdj. 
Check it out here: https://github.com/FlyGoat/RyzenAdj
